# Generated by Django 4.1 on 2022-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
    ]
