# Generated by Django 4.1 on 2022-09-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='profesion',
            new_name='Relacion',
        ),
    ]
