# Generated by Django 4.1 on 2022-09-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_rename_profesion_familia_relacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='Relacion',
            new_name='relacion',
        ),
    ]
